### ISSUE TITLE
Navigate contacts with J, K

### ISSUE THREAD

**Issue by AckslD** [isamert/scli#106]
Would be great if one could navigate contacts panel with capital J, K :)

**Comment by exquo** [comment]
Do you mean: while the focus is in the conversation pane, to change the current (opened) conversation with `J`/`K`, without having to press `Tab` to move to the contacts pane? Or make those keys do what `g`/`G` do (go to the top / bottom)?

**Comment by AckslD** [comment]
Without having to press `Tab`. I'm using [aerc](https://aerc-mail.org/) for mail where `J`/`K` goes to next/previous folder and I keep noticing that I try to do the same when I'm using scli.

**Comment by exquo** [comment]
Yes, this can be added. While the focus is on the chat messages, pressing `J`/`K` will change the opened chat and keep the focus in the (new) messages list.

**Comment by AckslD** [comment]
I was just wondering now actually if different keys would be better such as `ctrl+j`/`ctrl+k` or `ctrl+n`/`ctrl+p` since they could perhaps then also be used if focus is in the input-field.

**Comment by exquo** [comment]
That's a good point. 

The `Ctrl+n`/`p` combos would be claimed in the upcoming version for moving up and down the messages list when chat is in focus, and for cycling through commands history when the input line is in focus. (WIP)

The `Ctrl+j`/`k` should be a good alternative. It's not currently used for anything, and cycling through contacts' chats seems like the most natural assignment for it. 

`J`/`K` can be added for good measure, but will have effect only when the messages list is in focus, as above.

**Comment by AckslD** [comment]
Alt+j/k sounds good to me 👍 Although the optimal would be if that could be configured by the user :)

Regarding the issue with ctrl+j btw, is that only in certain terminal emulators? I'm using ctrl+j in vim without issues (kitty+zsh)

**Comment by exquo** [comment]
Good call about user-configurable key bindings, I've opened a new issue for that: #107

Turns out technically there is a distinction between key events for <kbd>Enter</kbd> and <kbd>Ctrl</kbd><kbd>J</kbd>: they produce 'Carriage return' and 'Line feed' respectively.

> `<CR>` or carriage return, technically used to mean *go to the start of the line*. `<NL>`, or newline aka line feed (usually called `LF`), was used to mean *go to the next line*. Over time, the distinction was lost in most applications.<sup>1</sup> Pressing <kbd>Enter</kbd> actually yields a carriage return, usually (try pressing <kbd>Ctrl</kbd><kbd>V</kbd><kbd>Enter</kbd> - you should see `^M` in Unix terminals). `<NL>`'s control code is <kbd>Ctrl</kbd><kbd>J</kbd>.
>
> https://vi.stackexchange.com/questions/4246/what-is-the-difference-between-j-ctrl-j-nl-and-ctrl-n-in-normal-mode/4249#4249

It's all the same to urwid though: `enter` is reported for both.

**Comment by AckslD** [comment]
> Good call about user-configurable key bindings, I've opened a new issue for that: #107
> 

Great 🙂

> Turns out technically there is a distinction between key events for <kbd>Enter</kbd> and <kbd>Ctrl</kbd><kbd>J</kbd>: they produce 'Carriage return' and 'Line feed' respectively.
> 
> > `<CR>` or carriage return, technically used to mean *go to the start of the line*. `<NL>`, or newline aka line feed (usually called `LF`), was used to mean *go to the next line*. Over time, the distinction was lost in most applications.<sup>1</sup> Pressing <kbd>Enter</kbd> actually yields a carriage return, usually (try pressing <kbd>Ctrl</kbd><kbd>V</kbd><kbd>Enter</kbd> - you should see `^M` in Unix terminals). `<NL>`'s control code is <kbd>Ctrl</kbd><kbd>J</kbd>.
> >
> > https://vi.stackexchange.com/questions/4246/what-is-the-difference-between-j-ctrl-j-nl-and-ctrl-n-in-normal-mode/4249#4249
> 
> It's all the same to urwid though: `enter` is reported for both.
> 
I see!

**Comment by exquo** [comment]
Implemented in [this](https://github.com/isamert/scli/tree/ui-misc-WIP) (alpha) branch. To be merged in 'mainline' soon.
