### ISSUE TITLE
Trouble following the README

### ISSUE THREAD

**Issue by remembertoremind** [isamert/scli#11]
Hi

I installed signal-cli from AUR and the README says `scli -u PHONE_NUMBER` which didn't work. Instead `signal-cli -u PHONE_NUMBER` gives the following error

```
usage: signal-cli [-h] [-v] [--config CONFIG] [-u USERNAME | --dbus | --dbus-system]
                  {trust,receive,listIdentities,link,unregister,updateGroup,quitGroup,listDevices,removeDevice,updateAccount,daemon,setPin,addDevice,listGroups,verify,send,removePin,register}
                  ...
signal-cli: error: too few arguments
```

Could this be caused by having the wrong version of urwid? The only python3 package I can find in the aur is `aur/pypy3-urwid 1.3.1-1 (+0 0.00%) (Orphaned) (Out-of-date 2018-01-18)`

**Comment by isamert** [comment]
The AUR package installs correct dependencies, so problem is not the `urwid` package.

Did you follow [linking process](https://github.com/isamert/scli#linking-your-device-and-using)? After that you need to run `scli -u PHONE_NUMBER`. If you done it, what is the output that `scli -u PHONE_NUMBER` gives?

**Comment by remembertoremind** [comment]
Yes, the linking went fine. After linking I ran `signal-client -u PHONE_NUMBER recieve` and thereafter `scli -u PHONE_NUMBER` but this gives me a `bash: scli: command not found`

**Comment by isamert** [comment]
Interesting, I just tried the AUR package and it installs the script just fine and I'm able to run `scli` directly. Maybe simply remove and reinstall the package? (You don't need to link again.)

Anyway, you can just clone this repository run `scli` from there:
```
git clone https://github.com/isamert/scli.git
cd scli
./scli -u PHONE_NUMBER
```

**Comment by remembertoremind** [comment]
Thanks for the quick responses and your awesome work. scli is a keeper :D 

Installing `scli-git` solved my problem and it's still linked. I'm trying to get a respons to see if messaging also works as intended.

**Comment by isamert** [comment]
Nice, thank you! I'm closing this issue, if you run across another issue just open a new one.

**Comment by remembertoremind** [comment]
Just the thing about adding contacts since I'm missing two :)

**Comment by isamert** [comment]
You can't add contacts trough `scli`, they should be synced from your phone.

You can try these to force sync:
- Close `scli`.
- Execute these commands:
```sh
signal-cli -u PHONE_NUMBER updateAccount
signal-cli -u PHONE_NUMBER receive
```
- Re-run scli: `scli -u PHONE_NUMBER`

If you really want to add contacts manually, you can mess with `~/.local/share/signal-cli/data/PHONE_NUMBER` file and try to add them manually but I don't believe that would do good.

If you believe that there is a real problem about syncing, you can open an issue on [signal-cli project](https://github.com/AsamK/signal-cli/).

**Comment by remembertoremind** [comment]
That is a great answer :) Thank you so much for your work. This is seriously the best project of the year.
