### ISSUE TITLE
Wrong timestamps handling

### ISSUE THREAD

**Issue by exquo** [isamert/scli#113]
If the clock on one of the devices in a conversation reports wrong values, these will be recorded and sent in messages' timestamps. The question is, how to handle those messages in scli. 

For instance: we get a message with a timestamp saying it's from the last month. There are already messages in this chat that are more recent. Should we insert the newly received message among the month-old messages, or place it at the very bottom of the chat?

There are these potential problems: 
- the clock is wrong on _scli device_ and we are _sending_ messages with wrong timestamps
- the clock is wrong on the _contact's device_ and we _receiving_ messages with wrong timestamps
- the clock is wrong on a _linked device_ and we are getting _sync_ messages with wrong timestamps

For reference, here's the official clients' behavior for message with a wrong timestamp:
- on sending device: insert the message in the chat according to the timestamp. 
	- timestamp in the past: it will be placed among messages from around that timestamp
	- timestamp in the future: subsequent messages with correct timesmaps will be inserted _above_ the "from the future" message
- on receiving device: place the message at the bottom of (i.e. last in) the chat. However, the date below the message is that of the timestamp.
- on linked device (receiving sync message): same behavior as on receiving device.

The behavior is the same whether 'device' is signal-desktop or signal-android.

This differs from scli in that newly received messages are always shown at the bottom of the chat, no matter what their timestamps are. We can consider adopting that behavior in scli.

See also: #105

**Comment by exquo** [comment]
Update: this can also occur when clocks are _correct_. 

If a message is sent from an official client while the device is offline (rather, attempted to be sent), it won't "fail" (to be re-sent later with a new timestamp). It will wait until the internet is back on, and then it'll be sent with the _original_ timestamp. Of course, in the meantime other messages in this chat might have been received.

**Comment by isamert** [comment]
> For instance: we get a message with a timestamp saying it's from the last month. There are already messages in this chat that are more recent. Should we insert the newly received message among the month-old messages, or place it at the very bottom of the chat?

I think inserting it to the bottom makes sense. If you just put it _where it belongs_, reader is just going to miss it. As you said this is also the behavior of the app. Simplest solution may be just attaching a local timestamp to the envelope and sorting messages based on that. I actually made a quick attempt to do this but it broke quite a lot of stuff as most of the logic is based on the timestamps.

**Comment by exquo** [comment]
I agree, we might want to replicate the official apps' behavior here. Especially since this applies not just to "wrong" clocks / timestamps, but whenever we receive a message with a timestamp older than the last message in that chat.

Yes, I would expect some complications here, since currently all functions assume that chats are always sorted by messages' timestamps. 

Some approaches I can think of:

- Simplest: focus on the new message in chat, wherever it is inserted, rather then on the last message, like we do now. If we get a message from the "past" in the currently opened chat, brining it into view / focus will help to not miss it; if the message is from a different chat, there is also a notification in the status line at the bottom and an unread counter in the contacts list.

- Have two lists of messages for every chat: 'sorted' and 'displayed' (the latter is passed to the ListWalker widget). 'Sorted' is always sorted by timestamp, and all the functions that rely on that fact still can find the messages they need. The displayed list we can order however we want (append new messages at the end, etc). 

- Add a new field to every received envelope: "received time" or something like that. Then we can have a single list sorted by that value. For sent and sync envelopes that do not have that field, use the "regular" timestamp, like we do now.

I haven't thought of this much, so I suspect some of these "solutions" might create more problems than than they will solve :)
