### ISSUE TITLE
signal-cli contacts import does not work properly

### ISSUE THREAD

**Issue by wherron01** [isamert/scli#118]
All of my contacts are listed as their phone number in groups, "NULL" in notifications, and do not show up in direct messages.  adding them all with :addcontact resolves this until i exit and reopen scli, but the issue returns then.  It does occasionally show the names from my phone, but this is erratic and seemingly random, and disappears upon opening any chat

**Comment by exquo** [comment]
Sounds like scli does not see any contacts in the `contactStore` in signal-cli's data file. Could you please check if there is anything in there? The data file is at 

	~/.local/share/signal-cli/data/+YOUR_PHONE_NUM

If there are no entries in the `contactStore` section, it would mean a problem upstream with signal-cli. The contacts in there should be same as those on your phone (assuming you've given the signal app on the phone the permission to access your contacts).

Likewise, after you do `:addContact` in scli, that contact should be added to signal-cli's data file. Could you try doing that and observing what happens to the data file, including any changes after scli restart?

**Comment by exquo** [comment]
One more wrinkle: getting a `CONTACTS_SYNC` envelope from signal servers replaces any local changes to contacts list with that on the phone (see #119). So while troubleshooting this, avoid using the signal app on the phone at the same time, lest it sends this 'contacts refresh' message.

**Comment by exquo** [comment]
This might be an instance of https://github.com/AsamK/signal-cli/issues/575.

**Comment by exquo** [comment]
The problem should now be fixed in the upstream (see https://github.com/AsamK/signal-cli/issues/575#issuecomment-831453275). Feel free to re-open if the issue reappers.
