### ISSUE TITLE
Colors for each user

### ISSUE THREAD

**Issue by remembertoremind** [isamert/scli#12]
It would be nice if the sclirc had a option to color each recipient/sender *OR* just one color for sender and receiver. So, sender is always color1 and receiver is alwasys color2.

**Comment by isamert** [comment]
I like the latter, simple and easy to configure. I will look into it.

**Comment by felleg** [comment]
+1 on this suggestion. 

I implemented it myself in a messy way (not worth doing a pull request now). To summarize I just ended up adding all possible Signal colors to the PALETTE list and replaced `txt.append(message)` by `txt.append(get_contact_color(contact), message[1])`.

**Comment by remembertoremind** [comment]
Any news on this about colors?

**Comment by exquo** [comment]
Maybe something along these lines:

Add a `--color` option with accepted values: 
- `none` / `mono` (default?)
- `two`. Optional: specify color for sender and receiver, with some sane defaults.
- `multi`. Optional: specify color for each contact (by e.g. giving a json/dict with phone numbers as keys and colors as values). Without additional parameters, use colors assigned by signal (on master device?), i.e. in signal-cli's data file's `contactStore` / `groupStore`.

All this would apply just to the text's foreground color. Background color could also be changed, but that would probably look too wild. 

Other considerations: 
- Will need to ensure the colors are readable on any given terminal with an unknown color scheme.
- Might have to query terminal's properties: whether it supports 256 colors, etc.

Any suggestions on user interface welcome.

**Comment by remembertoremind** [comment]
I'll give it some thought :)
