### ISSUE TITLE
Crash with `KeyError: contactStore` on startup

### ISSUE THREAD

**Issue by cycneuramus** [isamert/scli#125]
Hi all. Yesterday I updated to `signal-cli` [v.0.8.2](https://github.com/AsamK/signal-cli/blob/v0.8.2/CHANGELOG.md), and as of today, `scli` is crashing on start:

```
Traceback (most recent call last):
  File "/usr/bin/scli", line 4335, in <module>
    main()
  File "/usr/bin/scli", line 4320, in main
    coord = Coordinate()
  File "/usr/bin/scli", line 3694, in __init__
    self._contacts = Contacts(sigdata)
  File "/usr/bin/scli", line 997, in __init__
    self.reload()
  File "/usr/bin/scli", line 1000, in reload
    indivs_dicts, groups_dicts = self._sigdata.parse_data_file()
  File "/usr/bin/scli", line 882, in parse_data_file
    for cont in self._data['contactStore']['contacts']:
KeyError: 'contactStore'
```

I tried clearing out all data for both `signal-cli` and `scli` and then re-linking, with the same result.

I'd be grateful for your assistance here. Please let me know if you need additional information.

**Comment by taimon** [comment]
[Looks like the contacts API changed.](https://github.com/AsamK/signal-cli/commit/224d8194cc4f6cd91dfdeb71703b75ef67e0b208)

There is no longer a contactStore section in the data file. It looks like the contacts moved to the "recipients-store" file.

**Comment by exquo** [comment]
Indeed, the data storage schema has changed in the new version of signal-cli.

I will write incorporate the changes into scli's parser in a bit.

**Comment by taimon** [comment]
@exquo: Thanks for the quick and backwards-compatible fix.
