### ISSUE TITLE
Always highlight current chat

### ISSUE THREAD

**Issue by binarious** [isamert/scli#128]
It would be great if the current person/group would always be highlighted in the contact list. Otherwise it's hard to change with ALT+j/k without focusing the contact list.

**Comment by exquo** [comment]
Definitely, this should be added! Thanks for the suggestion!

**Comment by binarious** [comment]
Thanks for the quick implementation, @exquo! One thing I noticed: Selecting a contact with unread messages doesn't highlight it (maybe because the unread count is removed).

**Comment by exquo** [comment]
Yes, looks like that slipped by. Thanks!
Yes it's caused by the unread count being removed.
