### ISSUE TITLE
Messages on the same side

### ISSUE THREAD

**Issue by remembertoremind** [isamert/scli#13]
Messages are hard to read on when text is on both sides of the screen with only `<<`or `>>` to dertermine who sent it. It might be better to have the text on the same side and keep the `<<` and `>>` or combinate it with colors in the sclirc for sender/receiver.

**Comment by isamert** [comment]
It's possible to have messages on the same side now with `--one-sided` option. (It might be better to use it with `--show-names` option.) I will add a `--colorful` option in the future, but I believe these options solves this.
