### ISSUE TITLE
crash when member names are ints

### ISSUE THREAD

**Issue by mutax** [isamert/scli#131]
I noticed a crash when the members are numeric, as the join later expects strings.

Quickfix:

```
@@ -3027,7 +3033,7 @@ class ChatWindow(urwid.Frame):
             if name != num:
                 markup.extend([' (', num, ')'])
         else:
-            memb_names = [memb.name_or_id for memb in contact.member_contacts]
+            memb_names = [str(memb.name_or_id) for memb in contact.member_contacts]

```

**Comment by exquo** [comment]
According to signal-cli's sources, both contact's `name` and `number` should be of type `String`:
https://github.com/AsamK/signal-cli/blob/master/lib/src/main/java/org/asamk/signal/manager/storage/recipients/Contact.java#L16
https://github.com/AsamK/signal-cli/blob/master/lib/src/main/java/org/asamk/signal/manager/storage/contacts/LegacyContactInfo.java#L15

I've just tested renaming one of my contacts to `123` on my phone and syncing with signal-cli (the phone is the "master" signal device, signal-cli is linked with it). The new name is still stored as a string in signal-cli's data:

	$ cat ~/.local/share/signal-cli/data/+MYPHONENUM.d/recipients-store
	{
		"recipients" : [ {
		…
		}, {
			…
			"number" : "…",
			…
			"contact" : {
				"name" : "123",   # <-- note the quotes
	…

Do you have a contact with `"name" : 123` in signal-cli's `recipients-store`? (without the quotes around `123`; the integer might be different, of course) 
Is your signal-cli the "master" account or linked with the phone?
Have you by chance edited signal-cli's file manually?
