### ISSUE TITLE
Move cursor with ctrl arrow-key

### ISSUE THREAD

**Issue by NK308** [isamert/scli#133]
The commonly used shortcuts ctrl+leftarrow and ctrl+rightarrow for skipping the cursor along words seem to be not implemented for navigation in the input field yet and would be very useful.

**Comment by exquo** [comment]
Yes, we should implement this. It's been requested before (#88), in connection with the readline shortcuts.

In the meantime, with [urwid_readline](https://github.com/rr-/urwid_readline) you can use `Alt+F` and `Alt+B` to move one word forwards and back.
