### ISSUE TITLE
Text-aligment

### ISSUE THREAD

**Issue by remembertoremind** [isamert/scli#14]
If both sender/reveiver are on the same side, then this does not matter, but currently longer messages are scrambled and hard to read. If they are in left/right side of the screen they should be wrapped on their respected side of the screen, so it's easier to read.

**Comment by isamert** [comment]
I will try to make it work with having `>>` and `<<` opposite sides, if I cannot manage it I can go for having it with the same side and with #12 it will be more readable I hope.

**Comment by remembertoremind** [comment]
Moreover, it would be pretty nice if it was possible to make paragrafs in messages instead of one _long_ message. 

Maybe some wrapping of the text? I'm currently on a 1920x1080 display and the lines are getting long - perhaps an option for the sclirc like "wrap lines after 40 chars"?

**Comment by isamert** [comment]
I implemented your last request, you can use `--wrap-at N` option to change wrapping. What do you think about the readability now? Seems better to me but it still feels like something is missing.

**Comment by remembertoremind** [comment]
I just tried it out, and it's _way_ better. Good job!
