### ISSUE TITLE
Inline reply to specific message

### ISSUE THREAD

**Issue by zer0lean** [isamert/scli#148]
Hi,

In the native Android Signal app there's a feature to send a inline reply to a specific message. And when done from the native app scli shows it as a inline reply. But I can't find a way to actually do this from scli. Am I missing something or is this feature not available? Maybe there's limitations with signal-cli?

My suggestion would be to implement this feature with hitting 'r' (r as in reply) on a focused message to send a inline reply.

**Comment by exquo** [comment]
Replies / message quotes have just been added to signal-cli a few days ago (https://github.com/AsamK/signal-cli/commit/d13d150fe1c6b21dd53617cf7996d2876bc5db58). I'll add this functionality to scli when I have a bit more time. Haven't yet decided what the UX would look like..

For the keybinding - yes, I think `r` (for 'reply') would fit well. Also `q` (for 'quote'). (Both can be available, and either one can be used). 
There's one other candidate for the `r` key though - reactions (i.e. emoji), that are also in the plans. But I think it's more natural for most people to use `r` as a reply key. For reactions, we can find a substitute (maybe `e` for 'emoji'?).

**Comment by exquo** [comment]
The reply feature has been already been requested in #102. Let's track it in that issue.

**Comment by zer0lean** [comment]
Even tho I usually keep up to date with the Issues here I had totally missed this feature request, my bad.

**Comment by exquo** [comment]
No problem!
And the reminder is timely, with signal-cli just making this possible :)

**Comment by zer0lean** [comment]
That was just luck :)

**Comment by exquo** [comment]
Apparently, sending replies in signal-cli is *non-dbus* only, for now, so can't be used in scli. See https://github.com/isamert/scli/issues/102#issuecomment-1002790350
