### ISSUE TITLE
dunst notifications not working

### ISSUE THREAD

**Issue by cybvik** [isamert/scli#149]
I installed scli from the AUR on Arch. I have dunst and libnotify installed and running notifications via 'notify-send' work as expected.

But with scli, the notifications don't work. I've added the following line to my sclirc:
```
notification-command = notfiy-send scli 'New Message from %s'
```
But I get absolutely no notifications when I receive a new message.

**Comment by exquo** [comment]
Just a typo in your command 'not**fi**y-send' :)

Incidentally, you can use `scli --debug` to turn on verbose logging (printed to `~/.local/share/scli/log`) that shows the external commands being called.

Normally, when an external command is invalid, scli will print a warning at the bottom of the screen. But in this case it gets covered by the "New message from ..." line.
