### ISSUE TITLE
Cannot link: `Network Error` in the app.

### ISSUE THREAD

**Issue by mizzunet** [isamert/scli#153]
I'm getting "Network Error" after scanning QR and then clicking Link device in Android app. I tried several times.

Here's how I generated QR
![image](https://user-images.githubusercontent.com/10193999/148642718-4f65161a-155f-4add-a657-5cb149469e0c.png)

Though I was able to link with `signal-cli`. After this issue, I unlinked and linked with `signal-cli` and it works.

**Comment by mizzunet** [comment]
Hmm. I resolved it. My shell is `fish`, I ran `scli link` in `bash` and I got it approved. 

`signal-cli link -n "optional device name" | tee >(xargs -L 1 qrencode -t utf8)` also was ran at `bash`, in `fish` it wasn't returning anything

**Comment by exquo** [comment]
Yes sounds like something's up with the shell setup. (Maybe the network settings?)

I've tried in a fresh install of `fish`, and it has worked fine.
