### ISSUE TITLE
Support notification pictures

### ISSUE THREAD

**Issue by maximbaz** [isamert/scli#159]
It would be very nice to be able to get a profile picture of the sender rendered in the notification, just like Signal Desktop does.

Here's what I recommend to consider:

1. Find the path to sender's profile.

I can see some pics in `~/.local/share/signal-cli/avatars/contact-+<num>` and `~/.local/share/signal-cli/avatars/profile-+<num>`, not quite sure what's the difference, they seem to be somewhat duplicate, and I have more or `contact-` ones.

2. If image is not found, use hardcoded value `scli`.

3. Change default `NOTIFICATION_COMMAND` to be `notify-send -i "%i" scli '%s - %m'` (where `%i` is one of the two strings above)

This would achieve the following:

- If profile picture was found, it would be shown in the notification.
- If profile picture was not found, we will send a hardcoded `scli` value. 
    - user can then create `scli.<ext>` picture in any of the default icon locations, and this icon would be used as a "fallback icon"
    - user can also do nothing, and so if `scli` icon does not exist, it would be ignored by `notify-send`, i.e. the behavior would be as today, no icon.

**Comment by exquo** [comment]
Nice suggestion, thanks! Should be a pretty low hanging fruit for us to implement, too.

I'm also not sure why some avatar files start with `contact-` and other with `profile-`. Asked [upstream](https://github.com/AsamK/signal-cli/discussions/874). In practice, `scli` can check existence for both, and use whichever it finds.

In addition to the steps you describe, we can add a 'generic icon name' fallback, using one of the stock icon names (like `mail-message-new`) from the [freedesktop spec](https://specifications.freedesktop.org/icon-naming-spec/latest/ar01s04.html). I remember checking them for this purpose sometime back, but I guess I found them too "90s" looking :). And the users who really wanted a `scli` icon in notifications could add it in the `--notification-command`.

**Comment by maximbaz** [comment]
I agree, this is also a good approach to set default value to fallback to some existing icon!
