### ISSUE TITLE
Messages from sleep

### ISSUE THREAD

**Issue by remembertoremind** [isamert/scli#16]
If using a laptop which goes to sleep, mesasages are lost. When replying, replys comes up.

**Comment by isamert** [comment]
What do you mean exactly by _lost_? Are the messages getting deleted from the terminal or the new messages does not arrive? I can't test it for now, but I will as soon as possible.

**Comment by remembertoremind** [comment]
Sorry, not a very descriptive issue :)

If I  start a conversation, put my laptop to sleep, wake it up again and want to continue the conversation, all text is gone. It just look like the application was just started. Selecting a contact does not bring up prior conversations. Same as when scli is restarted.

**Comment by jeanlucthumm** [comment]
Experiencing the same thing. With the signal desktop app, when you first start it it shows all the previous messages from the last time it was started in a scrollable buffer. In scli, every time you restart it shows a blank conversation history and only registers new messages, and I haven't found a way to scroll back in history.

**Comment by exquo** [comment]
@jeanlucthumm, I think yours is a different issue: you are actually *restarting* scli, if I understand correctly. scli does not save chat history by default. You can enable it with `-s` or `--save-history` flag (see `scli --help`). Then the history would persist after scli restarts.

@remembertoremind, do you still have the original issue?

**Comment by remembertoremind** [comment]
@exquo, thanks for picking up on this issue. I haven't used scli for ages since this problem bugged me a lot. As I remember, scli came up as blank after my laptop came back from sleep.

However, I see a lot of work has been put into the code since I last tried, so please close this issue and I'll reopen when I get around to trying it out again :)

**Comment by exquo** [comment]
Sounds good, thanks! Yes there've been quite a few commits since then, so there's a chance it might have even been fixed inadvertently :)
