### ISSUE TITLE
Focus a conversation without moving cursor to messages/input field 

### ISSUE THREAD

**Issue by mark2185** [isamert/scli#166]
Sometimes I just want to focus a different conversation, not necessarily write anything there.

E.g. scrolling through the conversation list and pressing `Spacebar` to focus it, but the cursor remains on the contact's name.

**Comment by isamert** [comment]
You can use `l` to achieve this. `Enter` focuses on the input field but `l` only brings up the conversation without jumping to the input field.

**Comment by mark2185** [comment]
Ah, my bad, for some reason I thought `l` would focus the messages. Must've mixed it up with `Tab`. Thanks!
