### ISSUE TITLE
Download attachments on demand

### ISSUE THREAD

**Issue by mark2185** [isamert/scli#175]
I'm not even sure if this is possible, but I don't see any other way of sending a message.

Anyway, I'd like to be able to open attachments with `o`, but subsequently remove them from the disk for privacy purposes. Is it possible to redownload them?

**Comment by exquo** [comment]
That's not possible - signal messages are sent to the  devices only once. The messages are not stored on their servers (at least after they are delivered to all of the linked devices).

Re. privacy and disk storage, these recent discussions might be relevant:
https://github.com/isamert/scli/pull/169
https://github.com/AsamK/signal-cli/discussions/884
