### ISSUE TITLE
Install deps on Pop_OS! (Ubuntu)

### ISSUE THREAD

**Issue by avastmick** [isamert/scli#18]
Firstly, this is great - another Electron app hopefully goes away!

I use Pop_OS! (a Ubuntu flavour) and I needed to install the following deps:

`sudo apt install libunixsocket-java libmatthew-debug-java libnotify-bin notify-osd`

That includes the libs for notify-send - if used.

The main one was the unix-java lib. I had to install the `libmatthew-debug-java` and the right lib was installed... Maybe if you are a Java developer this isn't required.

**Comment by exquo** [comment]
Signal-cli no longer requires native dbus libraries. Thanks for the tip though!
