### ISSUE TITLE
scli cannot parse new signal-cli users

### ISSUE THREAD

**Issue by mikeevmm** [isamert/scli#182]
I tried doing a fresh installation of signal-cli/scli on my computer, but scli couldn't find my account, despite `signal-cli -u (...) receive` working fine. Rolling back to ` v0.7.0` of scli gets me

```
ERROR: Multiple accounts found. Run one of:
        scli --username=(...)
        scli --username=accounts.json
```

when running scli.

I think this has to do with how `signal-cli` now handles accounts; if I recall correctly, signal-cli used to create a folder named after the phone number under `~/.local/share/signal-cli/data` for each user. Now, it seems to create a folder with a random(?) sequence, and provide information mapping username to folder name under `~/.local/share/signal-cli/data/accounts.json`.

This could likely be approached by checking the existence of `accounts.json` and switching behaviours depending on that, but I'm not sure how migration can be handled.

**Comment by mikeevmm** [comment]
I think this is an easy fix, I'll try to submit a PR soon.

**Comment by mikeevmm** [comment]
There we go. Please review the above PR when convenient. Cheers.

**Comment by exquo** [comment]
Thanks for reporting this! The issue itself is the same as #180 that I have prematurely closed. I've left a comment in your PR.
