### ISSUE TITLE
Attachment name format

### ISSUE THREAD

**Issue by mark2185** [isamert/scli#194]
I'd love to be able to prepend the current date to the images I receive so I can find them more easily, is this something already implemented and I can't find it in the documentation or?

**Comment by exquo** [comment]
The attachments are saved by signal-cli, with their IDs as filenames. 

In principle, scli could choose to move and rename them after they are received. In case signal-cli is used by some program other than scli, this might break its expectations to the names and locations of attachments.

To be able to find attachments by date, you can sort the files in the attachments folder by the files' creation time.

**Comment by mark2185** [comment]
> The attachments are saved by signal-cli, with their IDs as filenames.

That's what I thought, thanks.

> In principle, scli could choose to move and rename them after they are received. In case signal-cli is used by some program other than scli, this might break its expectations to the names and locations of attachments.

Unless it copies it into `~/.cache/scli/attachments` or something.

> To be able to find attachments by date, you can sort the files in the attachments folder by the files' creation time.

Yup, that's my current approach.
