### ISSUE TITLE
Option to hide groups without a name

### ISSUE THREAD

**Issue by Nimmidev** [isamert/scli#196]
When using scli i have groups with weird names like "M4u70uK1FgpR83jSHWNBYcKne4DX/GtXjyIoFihxM5c=".
![scli group names](https://user-images.githubusercontent.com/21009721/175638141-89143b99-3a32-4bf9-b82c-3b254fdcc4a2.png)

After investigating a bit it seems like scli is using the group id if the name is null.

Output of `signal-cli listGroups`:
![signal null groups](https://user-images.githubusercontent.com/21009721/175630604-3454d6ed-1894-4580-a32d-945fc71af395.png)

If this is intended behavior it would be great if there was an option to hide groups with no name. Especially because these groups are the ones you are no longer part of i.e. you cant use them anyways.

(I am not sure if this is actually an issue with signal-cli. So if you think such entries shouldn't be in the `listGroups` output anyways  please tell me and i am gonna open an issue there.)

**Comment by exquo** [comment]
In line with following the official clients' behavior, signal-cli does not delete the group after leaving it (https://github.com/AsamK/signal-cli/discussions/975#discussioncomment-3093406). However, after leaving the group, its name in `listGroups` does not seem to change. 

To delete such group from signal-cli's list (and, correspondingly, scli's too), you can use your master device (signal on the phone), or signal-cli directly. That is, until the quit / delete group functionality is added to scli.

**Comment by exquo** [comment]
Correction: seems like deleting a group is not sync'd across devices. So we do need an option to delete groups from scli. To not reopen this issue, tracking it in the new one: #210.
