### ISSUE TITLE
Opposite of `enter`

### ISSUE THREAD

**Issue by rikhuijzer** [isamert/scli#197]
`enter` opens a conversation and focuses the input line (https://github.com/isamert/scli#keys). It's unclear to me how to get out of this "focus". Should `esc` maybe jump from the input line to the conversation? Then `h` can be used to jump to the contact list. At this moment, since I'm using `Alt + ...` already in my window manager config, there is no way to go back to the config list by only using the keyboard

**Comment by isamert** [comment]
A paragraph above explains the movements: https://github.com/isamert/scli#usage. You can simply use `Tab` or `Shift + Tab`.

**Comment by rikhuijzer** [comment]
Awesome. That works. Thanks for making this tool

**Comment by rikhuijzer** [comment]
I just wanted to add that I love this package. Thanks all for making it. I'm having a really great time sending text messages
