### ISSUE TITLE
Messages not showing up

### ISSUE THREAD

**Issue by remembertoremind** [isamert/scli#20]
I downloaded the newest version of the script, relinked my pc, started scli, send a message and when the reply came, scli puts it in the bottom of the screen like `New message from NULL` and the message does not show up in the conversation where the other messages are displayed.

**Comment by isamert** [comment]
I pushed a change to debug it better. Can you update the script and run it in debug mode?
- Remove the old log file: `rm ~/.local/share/scli/log`
- Start scli in debug mode: `scli --debug`
- Post the output of the log file after replicating the error.

I remember having this kind of error back in the day, `signal-cli` was outputting the message without the `source` property. If it's the same thing, I'll not be able to help but at least we can report it to `signal-cli`. Also `signal-cli -u PHONE_NUMBER updateAccount` may help.

**Comment by remembertoremind** [comment]
Removed the old log, got a message, but nothing showed up. I did a `signal-cli updateAccount` and `signal-cli receive` but nothing shows up when choosing my contacts :) 

```
INFO:root:NOT_A_MESSAGE:{'source': '+PHONE_NUMBER', 'sourceDevice': 1, 'relay': None, 'timestamp': 1552224978938, 'isReceipt': True, 'dataMessage': None, 'syncMessage': None, 'callMessage': None}
CRITICAL:root:NULL_CONTACT:{'source': '', 'sourceDevice': 0, 'relay': None, 'timestamp': 1552225010320, 'isReceipt': False, 'dataMessage': None, 'syncMessage': None, 'callMessage': None}
CRITICAL:root:get_contact_name:empty sender
INFO:root:NOT_A_MESSAGE:{'source': '', 'sourceDevice': 0, 'relay': None, 'timestamp': 1552225010320, 'isReceipt': False, 'dataMessage': None, 'syncMessage': None, 'callMessage': None}
CRITICAL:root:NULL_CONTACT:{'source': '', 'sourceDevice': 0, 'relay': None, 'timestamp': 1552225010320, 'isReceipt': False, 'dataMessage': None, 'syncMessage': None, 'callMessage': None}
CRITICAL:root:NULL_CONTACT:{'source': '+PHONE_NUMBER', 'sourceDevice': 1, 'relay': None, 'timestamp': 1552225087485, 'isReceipt': False, 'dataMessage': None, 'syncMessage': {'sentMessage': None, 'blockedNumbers': None, 'readMessages': [{'sender': '+PHONE_NUMBER', 'timestamp': 1552225068174}]}, 'callMessage': None}
CRITICAL:root:get_contact_name:empty sender
INFO:root:NOT_A_MESSAGE:{'source': '+PHONE_NUMBER', 'sourceDevice': 1, 'relay': None, 'timestamp': 1552225087485, 'isReceipt': False, 'dataMessage': None, 'syncMessage': {'sentMessage': None, 'blockedNumbers': None, 'readMessages': [{'sender': '+PHONE_NUMBER', 'timestamp': 1552225068174}]}, 'callMessage': None}
CRITICAL:root:NULL_CONTACT:{'source': '+PHONE_NUMBER', 'sourceDevice': 1, 'relay': None, 'timestamp': 1552225087485, 'isReceipt': False, 'dataMessage': None, 'syncMessage': {'sentMessage': None, 'blockedNumbers': None, 'readMessages': [{'sender': '+PHONE_NUMBER', 'timestamp': 1552225068174}]}, 'callMessage': None}
CRITICAL:root:NULL_CONTACT:{'source': '+PHONE_NUMBER', 'sourceDevice': 1, 'relay': None, 'timestamp': 1552225127666, 'isReceipt': False, 'dataMessage': None, 'syncMessage': {'sentMessage': {'timestamp': 1552225127666, 'message': 'Nej, det lyder ret godt :) hvor var det? Min weekend har været meget fin. Jeg kan ikke rigtig klage over noget. Eller jo, jeg er tyk, men det er jeg selv ude om ;)', 'expiresInSeconds': 0, 'attachments': [], 'groupInfo': None}, 'blockedNumbers': None, 'readMessages': None}, 'callMessage': None}
CRITICAL:root:get_contact_name:empty sender
INFO:root:NOT_A_MESSAGE:{'source': '+PHONE_NUMBER', 'sourceDevice': 1, 'relay': None, 'timestamp': 1552225127666, 'isReceipt': False, 'dataMessage': None, 'syncMessage': {'sentMessage': {'timestamp': 1552225127666, 'message': 'Nej, det lyder ret godt :) hvor var det? Min weekend har været meget fin. Jeg kan ikke rigtig klage over noget. Eller jo, jeg er tyk, men det er jeg selv ude om ;)', 'expiresInSeconds': 0, 'attachments': [], 'groupInfo': None}, 'blockedNumbers': None, 'readMessages': None}, 'callMessage': None}
CRITICAL:root:NULL_CONTACT:{'source': '+PHONE_NUMBER', 'sourceDevice': 1, 'relay': None, 'timestamp': 1552225127666, 'isReceipt': False, 'dataMessage': None, 'syncMessage': {'sentMessage': {'timestamp': 1552225127666, 'message': 'Nej, det lyder ret godt :) hvor var det? Min weekend har været meget fin. Jeg kan ikke rigtig klage over noget. Eller jo, jeg er tyk, men det er jeg selv ude om ;)', 'expiresInSeconds': 0, 'attachments': [], 'groupInfo': None}, 'blockedNumbers': None, 'readMessages': None}, 'callMessage': None}
```

**Comment by isamert** [comment]
I can only see messages that are sent from other devices (from your phone?) to other people, there are no incoming messages in the log. `scli` does not sync messages that are sent from other devices.

It's hard to tell what is going on from this log. As I understand the problem you are having is related to receiving messages but there are no incoming messages in this log, so I can't really say anything. It would be really helpful if you can open scli in debug mode and wait for a message, then send the log. 

And do you experience the receiving problem with all of your contacts or just a few of them?

**Comment by MalcolmMielle** [comment]
I also have this problem :/

**Comment by Syleron** [comment]
I as well am having the issue with all my contacts and the responses do appear to be inside my logs.

Any other thoughts?

**Comment by potyt** [comment]
Yup, this doesn't seem to work. All incoming messages are clearly seen, but it can't see who sent them - and therefore doesn't seem able to integrate them into any conversation. "New message from NULL" is all I ever get.

**Comment by mjuarezm** [comment]
I'm having the same issue.

**Comment by mjuarezm** [comment]
This seems to be the issue: [AsamK/signal-cli #245](https://github.com/AsamK/signal-cli/issues/245)

`signal-cli 0.6.5` supports receiving (but not sending) sealed sender messages

I updated it my `signal-cli` and now I'm receiving messages fine.

**Comment by isamert** [comment]
@mjuarezm thans for information! I guess this this resolved.
