### ISSUE TITLE
Not sending messages on fedora

### ISSUE THREAD

**Issue by MalcolmMielle** [isamert/scli#23]
Hello :),

Everything is working good on fedora up to the point where I need to send messages
Here is the debug log:

```
ERROR:root:send_message: exit code=1:err=b'Missing native library dependency for dbus service: no unix-java in java.library.path\n'
ERROR:root:input: b'Missing native library dependency for dbus service: no unix-java in java.library.path'
ERROR:root:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "./scli", line 539, in daemon_handler
    e = json.loads(line)
  File "/usr/lib64/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

I have install `libmatthew-java` where I believe the unix-java lib is so I'm a bit at a loss as to what I'm actually missing :)

**Comment by isamert** [comment]
I have no idea and I don't have a machine with Fedora installed to test it. `libmatthew-java` package should contain what is necessary it but it seems something is missing. Maybe it's a packaging issue?

**Comment by MalcolmMielle** [comment]
I found the [solution](https://ask.fedoraproject.org/en/question/134269/missing-unix-java-library/?answer=134271#post-id-134271).

Now I have another problem with some "New message from NULL" that I have to check up :)
