### ISSUE TITLE
Idea: Show list of commands in scli

### ISSUE THREAD

**Issue by ammgws** [isamert/scli#25]
It would be nice if we could see the list of available commands from within scli, instead of having to memorise them.

For example, perhaps the command `:h` could display a list of commands (easy?), or instead scli could predict as we type (hard). For the former I thought about using the status bar but it might not be suitable since it is single lined.

Any thoughts would be appreciated.

**Comment by isamert** [comment]
It would be nice to have this feature.

Hitting `Tab` may display possible completions on the status bar. But this will disable main purpose of `Tab` key while we are in the command mode. Using another key for completions will be unintuitive. 

Another option is the `?` key. I already added a popup window but it's still WIP. Can you try hitting `?` and state your opinions about it? How can I improve it?

**Comment by ammgws** [comment]
Oh, I didn't notice the `?` menu until now! Yeah, that would be good once it's finished.
