### ISSUE TITLE
Feature request: search contacts

### ISSUE THREAD

**Issue by mjuarezm** [isamert/scli#30]
Even though given signal's popularity this might be rare, users might have hundreds of contacts in the list. It would be good to have a way to search over them.

**Comment by isamert** [comment]
I'm thinking of this flow:
- User hits `/` while focused on users and a textbox appears at the bottom of the contacts pane.
- Every text user enters simply filters the contact list.
- When user starts a conversation the filter is cleared.

Does this flow satisfy your needs? I'll try to implement something basic as this whenever I find some free time.

**Comment by mjuarezm** [comment]
This would be great. Thanks so much for all the good work.

**Comment by isamert** [comment]
Now this works but a little bit different than I described before. Quoting from the README:

> For searching through contacts, you need to hit `/` while you are on the contacts window and start typing, contacts will be filtered out while you are typing. Hit `enter` to focus the results. Hitting `Esc` will clear the search.
