### ISSUE TITLE
Feature request: make shell kbd shortcuts available

### ISSUE THREAD

**Issue by mjuarezm** [isamert/scli#36]
It would be great to have shell keyboard shortcuts available in `scli`. I often navigate words using `Alt+f/b` and delete words using `Ctrl+w`. I wanted to implement this feature myself but couldn't find an easy way to make `urwid` respond to these commands.

**Comment by isamert** [comment]
I wanted to add this but never had a chance to do it, I will look into it whenever I find some time. But in the meantime you can try using `:e` command, it will open your default text editor for editing your message. Nice part of the `:e` command is that you don't need to remove anything if you already wrote something, just put the cursor at the beginning of the line and type `:e ` then enter. It will open your text editor with the message included.

**Comment by mjuarezm** [comment]
That's useful. Thanks.

**Comment by williamvds** [comment]
An attempt at upstreaming this behaviour was made in a closed patch request: urwid/urwid#34

However, there's an implementation of a `urwid.Edit` with readline shortcuts available in PyPI: https://pypi.org/project/urwid-readline

@isamert: would it be OK if I added urwid-readline as a dependency in a separate patch request? It could be optional, as readline behaviour isn't strictly necessary

**Comment by isamert** [comment]
I'm totally OK with that but it would be nice you introduce it as an optional dependency, like it simply falls back to old style of getting input if `urwid-readline` is not found. If you are not willing to put that much effort, that's also fine. 

By the way, thanks for your interest/contributions for the project!

**Comment by williamvds** [comment]
Great, I'll send a PR your way! Thank _you_ for accepting my changes!
