### ISSUE TITLE
Installation instructions unclear

### ISSUE THREAD

**Issue by captbuckrogers25** [isamert/scli#4]
When attempting to install and use scli The instructions are clear on how to install the prerequisites but something is missing in how to point scli to the signal-cli user.  When following all the steps of the installation in the readme I get my number linked to signal-cli then try to open scli -u +1########## and get:

```
./scli -u +1##########
Traceback (most recent call last):
  File "./scli", line 976, in <module>
    main()
  File "./scli", line 955, in main
    state = State(cfg)
  File "./scli", line 729, in __init__
    self.signal = Signal(cfg.username)
  File "./scli", line 312, in __init__
    raise Exception(self.user + " does not exist!")
Exception: +1########## does not exist!
```

I assume that this is because scli is looking for the user configuration in a different place than signal-cli left it, but I'm not sure how to resolve it.

EDIT:
Variable SIGNALSCI_DATA_FOLDER which is expected to contain user information is looking in ~/.local/share/signal-cli/data but signal-cli(0.6.2) appears to put the user information in ~/.config/signal/data

Altering lines 21,22 as follows allows full fuction:

```
#DATA_FOLDER = os.getenv('XDG_DATA_HOME', os.path.expanduser('~/.local/share'))
DATA_FOLDER = os.getenv('XDG_DATA_HOME', os.path.expanduser('~/.config/'))
#SIGNALCLI_FOLDER = os.path.join(DATA_FOLDER, 'signal-cli')
SIGNALCLI_FOLDER = os.path.join(DATA_FOLDER, 'signal')
```

**Comment by isamert** [comment]
I'm also on signal-cli 0.6.2 and it appears to be using `~/.local/share`. I assume you were using `signal-cli` from older versions and upgraded it? Because the [README](https://github.com/AsamK/signal-cli/#storage) of signal-cli clearly states that it uses `~/.local/share`. Anyways, I'll add a check for legacy path. Thanks for the report!

**Comment by captbuckrogers25** [comment]
I don't believe so, but I may have toyed with an earlier version of
signal-cli on this install. Once I got the path worked out and got xclip
installed the rest has worked a dream.

Thanks!
