### ISSUE TITLE
Strikethrough formatting breaks if ~~ is used instead of ~

### ISSUE THREAD

**Issue by twenty5151** [isamert/scli#43]
Both ~ and ~~ can be used for strikethrough in markdown, but ~~ breaks the formatting

## Prerequisites

* `use-formatting=true`

## Environment
Tested on kitty, alacritty, and xterm on manjaro linux.

## Steps to reproduce

* In three separate messages, type `*bold*`, `~onetilde~`, and `~~two~~`

## Expected results

* two should be rendered the same way as onetilde, with a strikethrough

## Actual results

![2020-02-25-01-01-36](https://user-images.githubusercontent.com/44771158/75207466-b3a35180-5770-11ea-8b33-d3cc8197b654.png)

## Details

Using `scli --debug` in around [line 1376](https://github.com/isamert/scli/blob/dc8d6b660428002271e28a611fbb7829fd8bc225/scli#L1376), the variable `m` returns:

```
INFO:root:STRIKETHROUGH:['*', ('bold', 'bold'), '*']
INFO:root:STRIKETHROUGH:['~', ('strikethrough', 'onetilde'), '~']
INFO:root:STRIKETHROUGH:['~', ('strikethrough', ''), '~', 't', 'w', 'o', '~', ('strikethrough', ''), '~']
```

The **expected behaviour** should be `['~~', ('strikethrough', 'two'),  '~~']`

A fix would also need to take care of cases like `~~strike1~~ nostrike ~~strike2~~`. In this case the **expected behaviour** would be `m = ['~~', ('strikethrough', 'strike1'),  '~~', 'nostrike', '~~', ('strikethrough', 'strike2'),  '~~']`

**Comment by yc-tsui** [comment]
Sorry for the confusion, but #45 fixes this issue. I think I should have made a new branch
