### ISSUE TITLE
Use TTY cursor for selecting list items

### ISSUE THREAD

**Issue by humenda** [isamert/scli#47]
Scli presents a list of contacts with a visual indication on which contact /
group is selected. The actual TTY cursor does not follow the selection and is
instead placed at the bottom of the screen (on the window frame).
For blind users using a screen reader, this makes Scli impossible to use because
the visual selection cannot be tracked. Instead, on selecting an item from the
list, the cursor should be explicitly set to the line and row of the item.  
This can be compared to `dialog --visit-items`.

I have not worked with Urwid myself, but I vaguely remember that the change
should be minimal, once clear which focus setter to call.

Thanks!

**Comment by isamert** [comment]
Thanks for informing, I will look into this as soon as possible!

**Comment by exquo** [comment]
I have just tried it, running `scli` inside a `tmux` session to determine the cursor's position inside a terminal. Pressing `Ctrl+b, [` (to enter tmux's copy-mode) shows the position of the cursor and also allows to move the cursor around. 

In scli, focusing different contacts in contacts list with `up` and `down` keys and checking on the location of the cursor shows the cursor in the rightmost cell position of the same line as the highlighted contact is in. The cursor's rightmost, last-cell position in a focused line is pretty conventional for terminal applications, as I understand. Mutt email client does the same in my test.

So this seems to be working normally. It might have changed in the UI code overhaul for [`v0.6.0`](https://github.com/isamert/scli/releases/tag/v0.6.0). If issues remain, please feel free to reopen.
