### ISSUE TITLE
emojis break UI

### ISSUE THREAD

**Issue by sethkush** [isamert/scli#48]
I have a contact name with emojis in it. The heart is supported and rendered, but the other one isn't, and this causes the remainder of the line to shift left, out of line with the rest of the UI.

![Screenshot from 2020-03-18 13-24-25](https://user-images.githubusercontent.com/9330400/76989024-1923d180-691c-11ea-99cd-6e54998b3fbb.png)

Edit: I tried using gnome-terminal, and it looks like the emojis are in fact supported, but they still break the UI, perhaps some sort of a width problem?

**Comment by isamert** [comment]
Probably an `urwid` issue but I will look into it.

**Comment by exquo** [comment]
Upstream issue tracking this problem: urwid/urwid#225

Looks like this is not really urwid's fault, but the terminal emulator's fault for printing a double-width char as a single-width. However, urwid devs are working on a workaround for this. 

Related:
https://stackoverflow.com/questions/54983257/curses-certain-emoji-flags-deform-terminal-output
https://pubs.opengroup.org/onlinepubs/009695399/functions/wcwidth.html

**Comment by maximbaz** [comment]
I'm not sure if it's the same bug, I discovered that some emojis in status bar can fully break the interface.

Here's how to reproduce:

- Have two contacts, say Jane and Joe.
- Open chat with Joe.
- Let Jane send you this message: `🟩`
- The message from Jane will be shown in the bottom in the status bar.

When this happens, this will break the interface, everything would as if shift up by one line above. If she keeps sending you this message again and again, things will get progressively worse.

**Comment by exquo** [comment]
Hm, can't reproduce. Although on my particular terminal that particular emoji does not seem to do any damage. But even the one that does cause the right line shift left by one character, like ❤️, does not cause any trouble when printed in the status line at the bottom of scli.

	┌───────────────┐
	│>> 🟩          │
	│>> ❤️          ││
	└───────────────┘

**Comment by maximbaz** [comment]
Thanks, your confirmation helped, I bisected my dotfiles and found the cause of the issue elsewhere, where I will report, just need to find some good repro steps using `urwid` alone 🙂

**Comment by exquo** [comment]
The issue seems to have been fixed since urwid v2.6.0 (https://github.com/urwid/urwid/commit/2f363f3daa1c3f4dd83e064ebeb5a7c05b0748e5). All the emojis that have previously displaced the layout don't cause the problems now. If there are still some symbols that cause this behavior, this issue can be reopened.
