### ISSUE TITLE
Enable Notifications argument error

### ISSUE THREAD

**Issue by n-xlkt** [isamert/scli#5]
The following command (included in README.md):

`scli -u +1234567890 --enable-notifications=true `

Results in the following error:
`scli: error: unrecognized arguments: --enable-notifications=true`

**Comment by isamert** [comment]
This is interesting, can you try `-n true` instead of `--enable-notifications=true`? If that does not work too, can you post the output of `scli -h`?

**Comment by n-xlkt** [comment]
`-n true` didn't work, here's the output for `scli -h`:
```
usage: scli [-h] -u USERNAME [--debug]

optional arguments:
  -h, --help            show this help message and exit
  -u USERNAME, --username USERNAME
                        Phone number starting with "+" followed by country
                        code.
  --debug
```

**Comment by isamert** [comment]
You are probably using an older version, can you update the script?

**Comment by n-xlkt** [comment]
As far as I can tell, everything is up-to-date.

**Comment by isamert** [comment]
I really have no idea then. Maybe the file is corrupted somehow? Does this command output anything?
```
cat PATH_TO_SCLI_SCRIPT | grep "enable-notifications" -A3 -B1
```

**Comment by n-xlkt** [comment]
Outputs the following:
`cat: PATH_TO_SCLI_SCRIPT: No such file or directory`

Looks like the issue is somewhere on my end, thanks!

**Comment by isamert** [comment]
Oh, my bad, I should be more explicit. I meant where you put the script by `PATH_TO_SCLI_SCRIPT` like `/home/your_user_name/scli`. Replace `PATH_TO_SCLI_SCRIPT` with that and run the command again.

**Comment by n-xlkt** [comment]
Nope, my bad, I should of grokked as much. Okay, so ran the command properly and it didn't output anything.

**Comment by isamert** [comment]
If the output is empty, that clearly means that your `scli` script is old (or somehow corrupted). Just download the script it again.
