### ISSUE TITLE
Notify user when send_message fails

### ISSUE THREAD

**Issue by exquo** [isamert/scli#52]
Currently if sending a message fails (for instance, if the internet connection drops), there is no notification given to the user. The message is appended to the chat history as if it has been sent successfully.

**Comment by exquo** [comment]
I can start working on the fix; if there is a preferred UI for this, let me know. Some of the possible solutions, in order of increased complexity: 
- Add some text to the body of the unsuccessfully sent message, e.g. `[failed]` and add it to chat window as normal, maybe also leaving the text in the input box for re-sending.
- Create an urwid pop-up box with a button offering to re-send the message.
- Set a 'failed' status next to the message text (e.g. an exclamation mark instead of the normal `<<`) and add the 're-send' button to the message information box (the one obtained with the `i` keypress).

**Comment by isamert** [comment]
OK, I saw this after commenting on #51 . I'm OK with all of the solutions that you presented. Here are my little comments:

- In first one, leaving the message in input box may confuse the user, not a big thing but may frustrate people.
- Second one seems very straight and nice.
- Third one is also nice, it may fit the already existing components. But also it may be hard to discover.

If you are still interested in this, I leave it up to you. I don't mind the if code gets complicated, at the end of the day it's just one python file.

Sorry about the late response.

**Comment by exquo** [comment]
Thanks for the comments, and no worries about the response time!

I should have mentioned #51 here too, so that it'd get cross-referenced in that PR. Adding here for completeness the option you've mentioned in that conversation: using the status bar at the bottom of the screen to notify about a send-failure. I think that's a good alternative, which can also be combined with any of the other approaches above. Particularly the third one: it can be used to help the users discover where to go to resend the message.

I'll get myself acquainted with `urwid`'s way of doing things and can start on one of those solutions. Hopefully it won't complicate the code much; after all, this boils down to a notification and a 're-send' button.
