### ISSUE TITLE
Stopped working since signal-cli 0.6.8

### ISSUE THREAD

**Issue by ndalliard** [isamert/scli#63]
There is a new release of [signal-cli 0.6.8](https://github.com/AsamK/signal-cli/releases/tag/v0.6.8). 

I updated and since then scli wasn't working anymore (the program itself starts fine, but wouldn't receive message nor could I send messages).

I reverted back to 0.6.7 for now.

Not sure how I can help to resolve this. It probably has something to do with dbus, cause since 0.6.8 there is no need for libmatthew. But as I said, no idea what the problem is.

Running on OpenBSD if that helps.

Maybe someone else is running into this problem.

**Comment by facadeproof** [comment]
Can't replicate on Void Linux. Can you try and run `signal-cli -u phone_no daemon` and see if it's a `signal-cli` issue?

**Comment by ndalliard** [comment]
Thanks @facadeproof, you are right, I get `org.freedesktop.dbus.exceptions.DBusException: Failed to connect to bus: Protocol not available`. Will look into it and open an issue over at `signal-cli`.
