### ISSUE TITLE
No attachments since signal-cli 0.6.8

### ISSUE THREAD

**Issue by facadeproof** [isamert/scli#65]
I can't receive any media attachments since signal-cli 0.6.8 and the history file is behaving very inconsistently although I have the setting save-history=true set on my ~/.config/sclirc.

Media messages from others are received but I can't see them on the tui when they are sent. I still receive them just fine through signal-cli as they are stored in the $XDG_DATA_HOME/signal-cli/attachments folder and the log file when one of these attachments is received looks like the following:

```
INFO:root:NOT_A_MESSAGE:{'source': '_', 'sourceDevice': 1, 'relay': None, 'timestamp': 1590608249691, 'isReceipt': False, 'dataMessage': {'timestamp': 1590608249691, 'message': None, 'expiresInSeconds': 0, 'attachments': [{'contentType': 'image/gif', 'filename': None, 'id': '3948276976530461244', 'size': 90112}], 'groupInfo': None}, 'syncMessage': None, 'callMessage': None, 'receiptMessage': None}
```

It should be noted that I can send attachments and see the attachments that I send from my end.

**Comment by exquo** [comment]
Confirming, this has started happening after updating to the new version of signal-cli. I'll try to look into what has changed there when I get a chance.
