### ISSUE TITLE
Sort contacts by recent messages.

### ISSUE THREAD

**Issue by elsehow** [isamert/scli#66]
I love this terminal UI - it works almost perfectly for me. Thanks very much for your work on it.

One suggestion: it would be extremely helpful if threads with unread messages were bolded and/or underlined in the contact list. Sometimes I get many messages while I'm gone, and it's difficult to see which threads I need to attend to.

EDIT: Based on @exquo's suggestion, updating the ask here to: threads with recent messages should appear higher in the contact list (rather than always appearing alphabetically).

**Comment by exquo** [comment]
scli already has (almost) this behavior - there is an unread message count, in bold, next to the contact's name in the contact list when there are new messages. There is also a counter for the total number of unread messages in the bottom right.

However, I think you raise a good point about seeing new messages at a glance. In the current implementation, if one has many contacts in the contact list (or a small screen / window size), one has to scroll through the list to check for the new messages. Seems like a better approach would be to do what signal-desktop does (and signal on mobile, and probably most of the messenger apps out there), namely: sort the contacts list by the "latest-activity", putting the conversations with the most recent sent or received messages at the top of the contact list. 

If you think this idea is in line with what you've had in mind, maybe we could change the title of this ticket to something like "Sort contacts by recent messages"? If I had misunderstood the request, please feel free to comment; and I could open a separate issue for the contacts sorting.

**Comment by isamert** [comment]
Yes, this should be the default behaviour. I'll be working on this, thanks for the suggestion!

**Comment by isamert** [comment]
With the latest commit, it works as expected but still groups are ordered between themselves and contacts also ordered between themselves. Not quite like the desktop/mobile signal app. If you think the contacts pane should be heterogeneous please open a new issue, and we can discuss this further there.

**Comment by elsehow** [comment]
Just pulled 4d12d93 - I see that the contact list does sort correctly at first, but resets to alphabetical after hitting Esc.

Steps to reproduce:
- Wait for messages to come in. Contacts are sorted by recent messages.
- Focus compose window.
- Tab to go back to contacts pane.
- Press Esc. Contacts will now be sorted alphabetically.
