### ISSUE TITLE
Make contacts pane heterogeneous

### ISSUE THREAD

**Issue by elsehow** [isamert/scli#69]
Currently, groups and contacts are listed separately in the contacts pane. Personally, I think the contacts pane should be heterogeneous, including both contacts and groups like in the desktop application. I am not sure why they would be separated. I am definitely willing to hear arguments to the contrary, though.

**Comment by exquo** [comment]
My two cents: my vote is also for the heterogeneous list. My typical usage is: I either know in advance whom I want to write to, and can search them with `/`; or I want to take a look at the recent conversations, in which case it doesn't much matter be they group or individual. 

That is not to say that having individuals and groups separated couldn't be useful in some cases. Maybe keep it as an option? Also, I  would probably choose to put individual conversations above the group ones, as I usually care more about the one-to-one conversations: when I get a message from an individual contact, it's directly for me, whereas sometimes a conversation in a group chat might not concern me as much.

@isamert, if you decide to go forward with this, I would be happy to implement it. I've actually already started looking into it in connection with #66, but got sidetracked with another part of code :)

**Comment by isamert** [comment]
I've implemented this behaviour but still like in #66 scli does not remember contacts order when it's restarted or `Esc` will override the recent messages order. I will implement permanently storing the contacts ordering by last message date but I believe it's a different issue, so I'm simply closing this.

Old behaviour can be activated by passing `--group-contacts` option but I kept the old ordering (first groups then contacts). @exquo what you said about ordering makes sense but for now I'll leave it as it is but I'm planning to change it later as you described.

**Comment by exquo** [comment]
Nice! 

How about this additional tweak: when the contacts view is heterogeneous (no separation between groups and individual contacts), add a **`[GRP]`**, (or something like that) to the end of each group name in the contacts window? This would allow for quickly seeing which contact is group and which is individual even when they are intermixed.

Ordering either individual contacts on top or groups on top has its advantages, I think it's just a question of personal preference.

Making old behavior as a config option is convenient, I was thinking along the same lines. The name `--group-contacts` was not very obvious for me though. It does make sense if I think about it like "group individual contacts together, and groups together", but it mixes up two senses of the word "group". I don't know what a better name would be, however.. Maybe `--sep-contacts-groups`? Or `--groups-ontop`?
