### ISSUE TITLE
Reload signal-cli's data file automatically

### ISSUE THREAD

**Issue by exquo** [isamert/scli#71]
Currently, scli only reads the signal-cli data file (`~/.local/share/signal-cli/data/+XXXXXXXXXX`) at startup. If it is updated while scli is running, scli needs to be restarted for them to be displayed. 

Possible updates include: 
- additions or removals of contacts or groups members
- contacts name changes (e.g. changes made from the master device) 
- re-keying / changes of safety numbers (e.g. a contact reinstalled signal on a new device)
- other things that are not currently relevant to scli:
	- 'archived' and 'blocked' status
	- contact's color and avatar
- ..more?

scli can use messages from the signal-cli daemon to trigger reloading the signal-cli's data file. We just need to document which events require reloading and what are the corresponding signal-cli messages. Those can then be checked in `State.on_receive_message()` to call `Signal.reload_data()`.

**Comment by isamert** [comment]
Related to this, I added a `:reload` command that re-reads the `signal-cli` data file
