### ISSUE TITLE
Allow renaming contacts

### ISSUE THREAD

**Issue by exquo** [isamert/scli#74]
Signal-cli has an `updateContact` method that allows to change contact's name. It might be useful to be able to do this from scli. This command can also be used to create a new contact.

Like #72, this is mostly a matter of adding the UI. I don't know what would be the most natural way to do it, maybe have a pop-up 'edit contact' dialog bound to some keypress (e.g. `e`) when the cursor is over the contact's name? Or have a `:renameContact` command?

Signal-cli's `updateContact` only changes names locally, in its own database. It needs a `sendContacts` call to sync it with server. Maybe this should be added as an addiotonal button in the 'edit contact' pop-up window.

**Comment by isamert** [comment]
I think a popup will complicate things. An `:renameContact` command would be a better fit. If commands become more discoverable, it would be even better. There is already a basic command completion with `Tab` key and basic contextual completion, like `:attach ~/<TAB>` would list files under your home folder. Likewise, `:renameContact <TAB>` would list all the possible contacts and the second argument would be the new contact name.

**Comment by exquo** [comment]
> It needs a sendContacts call to sync it with server.

From the `sendContacts` section of signal-cli's [man page](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#sendcontacts):

> This command should only be used if this is the master device.

So if signal-cli is not master (e.g. has been linked with a master on the phone), there is no way to update the contacts list on signal servers..
