### ISSUE TITLE
Failure to load SCLI_SORT_FILE on first execution

### ISSUE THREAD

**Issue by jpreiss** [isamert/scli#79]
The first time I run `scli` (using 8e068d461f7e1c52a6568a0ed969c2f3dcb9e04d) I get the following error:

```
Traceback (most recent call last):
  File "scli.py", line 1949, in <module>
    main()
  File "scli.py", line 1931, in main
    window = MainWindow(state)
  File "scli.py", line 1406, in __init__
    self._wleft = LeftWindow(self.state)
  File "scli.py", line 1094, in __init__
    self._wcontacts = ContactsWindow(self.state)
  File "scli.py", line 917, in __init__
    self.load_contact_order()
  File "scli.py", line 934, in load_contact_order
    with open(SCLI_SORT_FILE, 'r') as sort_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/<username>/.local/share/scli/sort'
```

Looking through the code, it doesn't seem like there's any attempt to create the file for the first time if it does not already exist.

**Comment by exquo** [comment]
Looks like a typo in the code. Should be fixed in #80.

**Comment by jpreiss** [comment]
Applying those (identical) changes locally fixed it for me.

**Comment by exquo** [comment]
@handsomematt: Nice parallel thinking :)

**Comment by handsomematt** [comment]
oh wow that timing, didn't notice you'd already fixed it 😅

**Comment by 0mp** [comment]
The patch works, I've integrated into into the FreeBSD port already.

**Comment by fireglow** [comment]
tag a new release for scli.

**Comment by 0mp** [comment]
> tag a new release for scli.

Oh yeah, a tag would be great. It simplifies packaging software a lot! :) 

Please create a tag if you can find a moment.
