### ISSUE TITLE
Everything opens, loads - but sending a new message does not display or send it

### ISSUE THREAD

**Issue by ventz** [isamert/scli#8]
Hi,

After linking, receiving the contacts/groups, and loading everything properly -- when I go to a group or contact and try to send a message, noticing two things:

1.) Whatever I type + send does not actually display on the screen after hitting enter
2.) It doesn't end up sending it (when verifying from the phone phone, and asking the remote party)

Otherwise, everything looks good UI wise/etc.

Not sure how to debug this. Thank you.

**Comment by isamert** [comment]
Does this happen everytime or sometimes? Also it should show the message you send on the screen even if it fails to send. Make sure you have the latest `scli` script.

Start `scli` with `--debug` then try to send some messages.  Then post the output of `~/.local/share/scli/log` here. (_WARNING_, the output may contain messages and phone numbers, just replace them before sending.)

Also can you try to send messages directly with `signal-cli`. Open `scli` as usual and then open a new terminal and run this command:
```
signal-cli --dbus send -m "test message" +RECEIVER_NUMBER
```
You can use your phone number as receiver for testing, the message should appear on your phone.

If the `signal-cli` command also fails, I suggest you to remove everything inside `~/.local/share/signal-cli` and relink your phone.

**Comment by ventz** [comment]
@isamert Thanks.

Downloaded the latest version (seem updated ~9 days ago) -- messages show up in the console with this version, but the receiving end does not get them.
(potentially related - they don't show up in the phone when sent from scli, and vice versa - if I send something from the phone, it doesn't show up within scli.)

The test for sending while having scli open with the `signal-cli --dbus send -m ...` causes this:

```
org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address
	at org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:244)
	at org.asamk.signal.Main.handleCommands(Main.java:69)
	at org.asamk.signal.Main.main(Main.java:50)
```

Deleted the dir, unlinked (from phone), and re-linked + received. Opened scli, and same thing, with the same error msg.

Started scli with `--debug`, and tried sending one message. Seeing this in the log:

```
~/.local/share/scli # cat log 
ERROR:root:input:b'org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address\n'
ERROR:root:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "./scli", line 339, in daemon_handler
    e = json.loads(line)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR:root:input:b'\tat org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:244)\n\tat org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:49)\n\tat org.asamk.signal.Main.handleCommands(Main.java:115)\n\tat org.asamk.signal.Main.main(Main.java:50)\n'
ERROR:root:Expecting value: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "./scli", line 339, in daemon_handler
    e = json.loads(line)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
ERROR:root:send_message: exit code=3:err=b'org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address\n\tat org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:244)\n\tat org.asamk.signal.Main.handleCommands(Main.java:69)\n\tat org.asamk.signal.Main.main(Main.java:50)\n'
```

Found this:
https://github.com/AsamK/signal-cli/issues/46

When running:
```
signal-cli --dbus-system send -m "tomato"  +PHONE
```

Getting:

```
Missing native library dependency for dbus service: no unix-java in java.library.path
```

So at this point, I need to set that up (on alpine linux - for some reason the java package claims it provides it)

**Comment by isamert** [comment]
You probably don't have a dbus service running. So you need to install `dbus` package, if you don't have it. Then start it (as far as I understand Alphine linux uses openrc, so these are openrc commands and I'm not really sure about them):
```
rc-service dbus start
```

If you want to add it to your startup:
```
rc-update add dbus
```

**Comment by isamert** [comment]
Also currently the messages you send from your phone won't appear in scli. I didn't really look it up but there is no way to gain that information through `signal-cli`.

**Comment by CivilianZero** [comment]
What would you recommend for MacOS users having the same problem?

**Comment by ventz** [comment]
@isamert Thanks. Not sure why, I thought if you didn't have the system-dbus, the app uses the "application" dbus -- that is,  your app creates a dbus emulation, and signal-cli talks to it.

Feel free to close this (I don't want to close it in case @CivilianZero wants more info here).

**Comment by isamert** [comment]
@CivilianZero I found [this](https://github.com/AsamK/signal-cli/issues/145) issue on `signal-cli`, but there seems to be no answers/solutions. You can try installing and enabling `dbus` on your machine and see if it works on your setup:
```
brew install dbus
brew services start dbus
```

If you make any progress and hit another issue please let me know. I'm closing this issue for now as it's really a `signal-cli` issue.
