### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by exquo** [isamert/scli#85]
Suggested in #79. Once the recent commits are field-tested enough, a stable release can be tagged. @isamert, do you have any preferences on a versioning scheme?

**Comment by isamert** [comment]
`semver` doesn't make sense in case of GUI/TUI applications I assume, but we can adopt something similar nonetheless. We can simply increment major version when something big is added or something completely changes, for simple additions, simple features we can increment the minor version and we can increment patch whenever there is a bugfix or something along the lines of this. Kind of feeling based versioning :). If you have a better idea I'm all for it, I don't have experience on this kind of thing but something simple is what I prefer.

**Comment by exquo** [comment]
Feeling-based versioning sounds good :). Then let's test out the current master and if nothing serious comes up, it can be tagged (0.1.0?).
