### ISSUE TITLE
Ctrl-Left/Right doesn't jump words as expected from readline shortcuts

### ISSUE THREAD

**Issue by paulrouget** [isamert/scli#88]

**Comment by exquo** [comment]
Apparently `Ctrl+Left/Right` is not part of readline shortcuts, but is a terminal-emulator-specific behavior. For instance, `xterm` and `gnome-terminal` have it, but `urxvt` does not. See
https://readline.kablamo.org/emacs.html
https://wiki.archlinux.org/index.php/Readline#Fast_word_movement

It might be a good idea to have this (extra) functionality in urwid-readline anyway, though. You can open an issue for it here:
https://github.com/rr-/urwid_readline/issues
