### ISSUE TITLE
Messages fail to send

### ISSUE THREAD

**Issue by scottwn** [isamert/scli#90]
Every time I try to send a message it fails with the error
> Message "hello..." failed to send. Press 'r' on message to re-send.

Focusing the message and pressing 'r' doesn't seem to do anything.

Am I doing something wrong?

**Comment by scottwn** [comment]
Caused by a local Java conflict, working now, thanks!

**Comment by Ostropol** [comment]
> Caused by a local Java conflict, working now, thanks!

How did you manage to do this? I have the same issue.

**Comment by scottwn** [comment]
I had to point to JRE 11 using `alternatives` and make sure that `JAVA_HOME` was also set correctly to match it. `signal-cli` requires JRE 11. Here are a couple decent overviews of how to handle Java versions:

https://medium.com/@ayeshajayasankha/how-to-install-and-switch-between-alternative-java-versions-66b3671fc382

https://linuxize.com/post/install-java-on-ubuntu-20-04/
