### ISSUE TITLE
Python error on formatting contact list

### ISSUE THREAD

**Issue by jeroenops** [isamert/scli#94]
Hi,

I use `scli` on FreeBSD since months. However, when I start it right now, it throws an error that seems related to something in the contact list:

```
Traceback (most recent call last):
  File "/usr/local/bin/scli", line 2485, in <module>
    main()
  File "/usr/local/bin/scli", line 2472, in main
    window = MainWindow(state)
  File "/usr/local/bin/scli", line 1645, in __init__
    self._wleft = LeftWindow(self.state)
  File "/usr/local/bin/scli", line 1324, in __init__
    self._wcontacts = ContactsWindow(self.state)
  File "/usr/local/bin/scli", line 1120, in __init__
    self.reload()
  File "/usr/local/bin/scli", line 1135, in reload
    self.set_contacts(self.make_formatted_contacts_list())
  File "/usr/local/bin/scli", line 1259, in set_contacts
    contact_widgets = [mk_contact(x) for x in contacts]
  File "/usr/local/bin/scli", line 1259, in <listcomp>
    contact_widgets = [mk_contact(x) for x in contacts]
  File "/usr/local/bin/scli", line 1252, in mk_contact
    widget = urwid.Text(self.mk_contact_widget_markup(x))
  File "/usr/local/bin/scli", line 1174, in mk_contact_widget_markup
    profile_name = self.state.signal.get_contact_profile_name(contact)
  File "/usr/local/bin/scli", line 1099, in get_contact_profile_name
    return profiles_map[contact_id]['profile']['name']
TypeError: 'NoneType' object is not subscriptable
```

I have tried a couple of things:

* Upgrading the package to the latest revision from the GH repo,
* Reinstalling both `signal-cli` and `scli`,
* Running `signal-cli -u [number] retrieve`.

However, that didn't change anything. Is there a fix for this without losing the files already retrieved and the history on disk (with the `-s` argument)?

**Comment by jeroenops** [comment]
I've fixed it by replacing `~/.local/share/signal-cli/data/[user]` from backup that was a few days old. Yet, I do remain curious to what the issue here is :)

**Comment by jeroenops** [comment]
Hmmm, exact the same error after I run `signal-cli -u [number] retrieve`. It seems that the `retrieve` command fetches some data that causes this particular crash...

**Comment by jeroenops** [comment]
Okay, I've debugged something further and found a possible cause:

In the datafile (`~/.local/share/signal-cli/data/[user]`), there were lines that contained the string `"name" : "",`. Replacing them all with _some_ contents fixed the issue - even after running `signal-cli -u [number] retrieve`. This might be related to issue #60.

**Comment by exquo** [comment]
Thanks for reporting!

This is caused by the new format of the `profileStore` part of signal-cli's data file in v.0.6.12, allowing `"profile" : null`. 

The reason renaming the empty contact names (`"name" : ""`) had worked is that scli could not locate their profiles at all, and did not attempt to further query them for profile names.
