### ISSUE TITLE
Emoji in group name

### ISSUE THREAD

**Issue by AckslD** [isamert/scli#97]
I have a group with an emoji in the group name. Seems `scli` thinks this has width "2" and makes other things, e.g. the chat, miss-aligned. See screenshot below:

![gscreenshot_2021-01-11-104741_2](https://user-images.githubusercontent.com/23341710/104166193-b0ea3300-53fa-11eb-8c91-9bca360eae97.png)

**Comment by exquo** [comment]
Looks like the same as #48. Please reopen if yours is a different problem in some way.

**Comment by AckslD** [comment]
Oh sorry, seems to be the same indeed

**Comment by exquo** [comment]
No worries!
