### ISSUE TITLE
Ignore non-messages?

### ISSUE THREAD

**Issue by AckslD** [isamert/scli#98]
I'm wondering if certain non-messages should be ignored? For example if someone "likes" (puts an emoji on a message) this currently shows up as an empty message which is a bit confusing. Same for when someone accepts invitation to a group.

**Comment by AckslD** [comment]
Alternatively if what actually happens is printed as a message.

**Comment by exquo** [comment]
Yes, good call. 

"Reaction" messages (aka "likes") have recently been added to signal-cli, so we can now display those properly in chats. (#99)

The other "non-messages" shouldn't send notifications. I'll make the testing for a "real" message more stringent. 

If there are any other "non-messages" that scli sends notifications about, feel free to add them here too.
